apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namePrefix: polynote-

configMapGenerator:
- name: configmap
  files:
  - config.yaml=config.yaml
